---

api_id: 8857087
api_hash: 55f503a96cfdbac2d30d752d47d5a049
app_short_name: emmmm

messages:
  one: |
     ✅Royal Chirstmas

     🟣Massive Marketing
     ⚪️MCap : 10k 
     ⚪️Fastrack CG & CMC Listing

     0 x57602f09b3d76d44f5a29768cc307402aeed52ac

     Tgram = RoyalChristmasToken
  two: |
    this is message 2
    again, it can be whatever you want it to be
    so you can have some variation

raid:
  luckycatchinese:
    message_type: one
    # this is in seconds, so the below example is equal to 5 minutes
    # we recommend at least 900 seconds, which is equal to 15 minutes
    wait_interval: 10
    # this is in seconds, so the below example is equal to 1 minute
    increase_wait_interval: 60
    # this assumes the image's path is relative to the script `tg_shill_bot.py`
    image: 
  arzanocrypto:
    message_type: one
    # this is in seconds, so the below example is equal to 5 minutes
    # we recommend at least 900 seconds, which is equal to 15 minutes
    wait_interval: 10
    # this is in seconds, so the below example is equal to 1 minute
    increase_wait_interval: 60
    # this assumes the image's path is relative to the script `tg_shill_bot.py`
    image: 